version: "3.8"

services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: dfg-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: anish@developforgood.org
      PGADMIN_DEFAULT_PASSWORD: anish
    ports:
      - "8889:80"
    hostname: pgadmin
    depends_on:
      - postgres
  redis:
    hostname: redis
    container_name: dfg-redis
    image: redis
    ports:
      - "6379:6379"
  redis-insight:
    hostname: redis-ui
    container_name: dfg-redis-ui
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis
  pantheon-server:
    hostname: pantheon-server
    container_name: pantheon-server
    build:
      context: .
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - redis
